### ISSUE TITLE
WARNING: 'aclocal-1.15' is missing on your system.

### ISSUE THREAD

**Issue by rafalars** [Hypsurus/ftpmap#5]
tried running: apt-get install automake and apt-get install autotools-dev, but the error continue.
using Linux Mint 17.1 64bits

I know this project is inactive but i wanted to study this code so i could build my own ftp scan...

thanks :D

**Comment by rafalars** [comment]
If anyone get this error try creating a "fake" symlink to fool the system.
$ sudo ln -s /usr/bin/aclocal-1.14 /usr/bin/aclocal-1.15
then after $ make
$ sudo rm /usr/bin/aclocal-1.15

**Comment by Hypsurus** [comment]
Hey @rafalars

You can send a PR for README.md with this solution?  

Like this:

###### Troubleshooting

1. [ISSUE]
(solution)


Thank you!
