### ISSUE TITLE
Fingerprint issue

### ISSUE THREAD

**Issue by enderax** [Hypsurus/ftpmap#7]
Hi, 
I've tested ftpmap on Mac OS X 10.10.3. The fingerprint process is not working against to Microsoft FTP server. And strangely, fingerprint percent exceeds %100 then it said "Error: Failed to create a new socket" after %173. Here is log:

`_:: Starting FTP-Map 0.15 - Scanning (X.X.X.X:21)...
:: FTP Banner: 220 Microsoft FTP Service
:: Trying to login with: anonymous:anonymous@localhost
:: (Failed) 530 User anonymous cannot log in.
:: SYST command failed.
:: Trying to detect FTP server by banner...
:: Trying to detect FTP server by fingerprint...

Fingerprint:
{
	0UL, "Microsoft FTP",{
2933,2450,2933,2933,2933,2933,2933,2933,2933,2918,3893,4163,2933,2933,2921,3055,2935,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,3030,2933,2933,2933,2933,2933,2933,2933,3411,2991,1001,3452,3032,3052,2896,2977,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2923,3001,3128,2997,3179,3629,3002,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,2933,3567,2551,2919,2904,2909,2885,2820,6509,7347,6663,5689,7184,6623,7460,8620,7273,7181,7247,5723,6390,6431,5010,5706,6709,7113,7365,6753,8089,5889,5471,7493,7983,7805,8084,7128,6851,6933,8610,7656,5823,8674,7245,6982,7808,7092,7980,6971,7327,7567,8098,6798,6827,7519,7264,8066,6853,8217,8038,7012,8318,6754,8822,9065,7215,8652,8179,8302,8448,7528,6943,7699,8456,7660,7839,7929,8193,7429,8553,7705,8848,7167,6911,7224,7598,7149,7721,7730,7117,9359,9877,6088,8317,10319,10513,4833,7228,6315,6605,6025,7253,8945,9620,8084,5696,7554,8445,6611,8669,6089,6943,7494,6653,%_`

**Comment by Hypsurus** [comment]
Maybe it's the host firewall? 
Also ftpmap replaced with [skod](https://github.com/Hypsurus/skod), 
try to use nmap, ftpmap code is only for learnning the how to FTP proto works.

**Comment by enderax** [comment]
OK, I will check it out
