### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kd4zay** [Hypsurus/ftpmap#8]
Hi, 

I get a Segmentation fault error when issuing the following command:
 ftpmap --scan --server 127.0.0.1:21

i was able to get it to build on kali with a little help.

any ideas ?

Thanks in advance.

**Comment by Hypsurus** [comment]
Hello @kd4zay.

Use this `ftpmap -Ss 127.0.0.1` , FTP map by default uses port 21
To provide port use `--port`

Note: FTPMap is no longer under active development  

Hope you have a great day!
